# DaemonSet

# A DaemonSet ensures that all (or some) Nodes run a copy of a Pod. As nodes
# are added to the cluster, Pods are added to them. As nodes are removed from
# the cluster, those Pods are garbage collected. Deleting a DaemonSet will
# clean up the Pods it created.

# Some typical uses of a DaemonSet are:
# - running a cluster storage daemon on every node
# - running a logs collection daemon on every node
# - running a node monitoring daemon on every node

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
        - name: fluentd-elasticsearch
          image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
