# The .github/workflows directory contains YAML files with the pipeline configuration.

name: Go + PostgreSQL

on: [push] # This pipeline is triggered on push operations only

# This is the Linux image that is going to be used. As the Go binary is built inside a
# Docker image, we do not need to install Go on the Linux VM.
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job     can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.19"
      - name: Publish Docker Image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          IMAGE_NAME: gopost
        run: |
          docker images
          docker build -t "$IMAGE_NAME" .
          docker images
          echo "$PASSWORD" | docker login --username "$USERNAME" --password-stdin
          docker tag "${IMAGE_NAME}" "$USERNAME/${IMAGE_NAME}:latest"
          docker push "$USERNAME/${IMAGE_NAME}:latest"
          echo "* Running Docker Image"
          docker run ${IMAGE_NAME}:latest
