# Secret
# Secrets provides a way to distrubute credentials, keys, passwords. or secret date to the pods.
# There are three main ways for a Pod to use a Secret:
#    - As files in a volume mounted on one or more of its containers.
#    - As container environment variable.
#    - By the kubelet when pulling images for the Pod.

# To generate secrets using files:
# echo -n "root" | base64
# cat /etc/foo/username.txt # admin
# cat /etc/foo/password.txt # 1f2d1e2e67df
# kubectl create secret generic <secret-name> --from-file=<username.txt>  --from-file=<password.txt>

# To generate secrets using yaml file
apiVersion: v1
kind: Secret
metadata:
  name: <secret-name>
type: Opaque
data:
  <key>: <value>
  # ...

# Using secrets on a Pod as a variable environment
spec:
  volumes:
    - name: foo
      secret:
        secretName: <secret-name>
        optional: false # default setting; "secret-name" must exist
  containers:
    - name: <container-name>
      image: <image-name>
      volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: <secret-name>
              key: <key>
              optional:
                false # same as default; "mysecret" must exist
                # and include a key named "username"
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: <secret-name>
              key: <key>
              optional:
                false # same as default; "mysecret" must exist
                # and include a key named "password"
  restartPolicy: Never
